=== bacongobbler/bcit-swag/data/roster.dtd
<!ELEMENT roster (member+)>
<!ELEMENT member (number, position, firstname, lastname, age, weight, img)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT weight (#PCDATA)>
<!ELEMENT img (#PCDATA)>

<!ATTLIST roster team CDATA #REQUIRED>

=== bacongobbler/bcit-swag/data/roster.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE roster SYSTEM "roster.dtd"> 

<!--
Displays the 2012 roster for the Seattle Seahawks,
an american football team in the NFL.

@author Jason Bolanos
-->

<roster team="Seattle Seahawks">
    <member>
        <number>3</number>
        <position>QB</position>
        <firstname>Russell</firstname>
        <lastname>Wilson</lastname>
        <age>23</age>
        <weight>206</weight>
        <img></img>
    </member>
</roster>
